### ISSUE TITLE
feat: customize a `blacklist` of mode where `topspace` should not be activated

### ISSUE THREAD

**Issue by danilevy1212** [trevorpogue/topspace#3]
**Is your feature request related to a problem? Please describe.**

Some modes, like `telega`, `org-agenda-mode` look really bad with this mode active, which prevents me from using the `global-topspace-mode`

**Describe the solution you'd like**
It would be nice if there was a `defcustom` variable to customize certain modes where the user does not wish this mode to be active.

**Comment by trevorpogue** [comment]
Hi, thanks for the input! This sounds like a good idea and I can implement this. However, first I have some questions for you:

- Is this issue fixed if you set `topspace-autocenter-buffers` to nil? Do this by adding this to your config file then restarting Emacs: `(custom-set-variables '(topspace-autocenter-buffers nil))`. I would expect everything to look the same whether `topspace-mode` is enabled or not in any given buffer when that variable is set to nil, unless you scroll above the top line in that buffer (but please prove me wrong if this is not the case).

- Could you provide a screenshot of what looks bad in these modes? I am trying out `org-agenda-mode` with `topspace-mode` but it's acting as expected from my end (and having issues getting `telega` installed).

- What Emacs version are you using? (use <kbd>C-h C-a</kbd> to see it)

I think it will still be a good idea to implement the feature you mentioned. I propose making a customizable variable called `topspace-enable-from-global-p-function` (or something along those lines) for this that can be set to a user function, and the user function can return non-nil or nil to signal that `topspace-mode` should be enabled or not from `global-topspace-mode` in that buffer, respectively. Does that sound good to you?

**Comment by danilevy1212** [comment]
Hey @trevorpogue! I'll answer in order:

- The issue does go away and exactly like you said, it looks `topspace-mode` wasn't turned on, except being able to move the visual lines beyond the first line.
- Sure! Here it goes :) For telega:
![image](https://user-images.githubusercontent.com/32525865/156634207-a80d4e74-3a6a-40db-b2a7-da52fe98095d.png)
For org-(super)-agenda:
![image](https://user-images.githubusercontent.com/32525865/156634436-c12ae391-76d6-4410-b426-3c6d4608f03a.png)
- I am using doom emacs, emacs-version: -> `GNU Emacs 28.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.31, cairo version 1.16.0)`

The solution you propose sounds very very flexible, I like a lot :)

**Comment by trevorpogue** [comment]
Okay thanks for the information, it's helpful. I'm working on the feature. In the meantime, I was curious, do you like the overall behaviour when `topspace-autocenter-buffers` is on (set to t), or do you like it better when it's turned off (set to nil)? I'm just trying to figure out if people would prefer it to be enabled or not by default.

**Comment by danilevy1212** [comment]
Definitely on by default for me. Honestly, without it on i would just forget it's there.

**Comment by trevorpogue** [comment]
Okay that's good, I have the same feeling.

**Comment by trevorpogue** [comment]
So based on the screenshots its behaving as designed except its pushing the text in the top window a few lines too far down. I've noticed this happens in buffers with little pictures/emoticon type characters in it which make the line height taller than before, but that is a separate issue for some other time.

I've added a variable called `topspace-active` which can be set to t, nil, or a predicate function. When the variable or function returns t, `topspace-mode` will act normally as before. When the variable or function returns nil, `topspace-mode` will technically be on, but effectively will be off and there would be no difference in the buffer compared to if the mode is off.

This is the most flexible way possible to filter the mode being on/off from `global-topspace-mode` as far as I can tell, because this way the mode can be activated/deactivated in real time based on any custom circumstance. However, with an enable-from-global approach like we talked about earlier, the mode can only be allowed/prevented from being turned on after manually turning on `global-topspace-mode` or after major modes change, as far as I can tell.

I also made `topspace-autocenter-buffers` allowed to be a function to let the feature be activated/deactivated based on any custom circumstance.

**Comment by danilevy1212** [comment]
Thank you so much! @trevorpogue 

For anyone else that is interested, this is how I have it configured now, it works like a charm :)

```lisp
(use-package! topspace
  :config
  (defun dan/topspace--active-p ()
    (not (memq major-mode '(vterm-mode org-agenda-mode))))
  :custom
  (topspace-active #'dan/topspace--active-p)
  :hook
  (doom-first-buffer . global-topspace-mode))

```
